[container.image]
repository="PasinduLakshan99"
name="twilio"
tag="0.1.0"

[[cloud.config.files]]
file="./Config.toml"

[cloud.deployment]
min_memory="512Mi"
max_memory="1Gi"
min_cpu="250m"
max_cpu="500m"

[cloud.deployment.autoscaling]
min_replicas=2
max_replicas=5
cpu=70
memory=80

[cloud.deployment.probes.liveness]
port=9090
path="/sms/liveness"

