openapi: 3.0.1
info:
  title: Sms
  version: 0.1.0
servers:
  - url: "{server}:{port}/sms"
    variables:
      server:
        default: http://localhost
      port:
        default: "9090"
paths:
  /notify:
    post:
      operationId: postNotify
      parameters:
        - name: toMobile
          in: query
          required: true
          schema:
            type: string
<<<<<<< HEAD

        - in: query
          name: text
          description: text to be sent
=======
        - name: message
          in: query
>>>>>>> c5576e7df050d756916e3567b6c3e9919e52b5a1
          required: true
          schema:
            type: string
      responses:
        "202":
          description: Accepted
        "400":
          description: BadRequest
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorPayload"
  /liveness:
    get:
      operationId: getLiveness
      responses:
        "200":
          description: Ok
components:
  schemas:
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
